name: Eval

run-name: ${{ inputs.run-name != '' && inputs.run-name || github.workflow }}

on:
  workflow_dispatch:
    inputs:
      runs-on:
        required: true
        type: string
      shell:
        default: bash
        type: string
      run:
        required: true
        type: string
      # NOTE: Disabled because GitHub Actions fails at job setup when environment evaluates to empty string ("").
      # environment:
      #   required: false
      #   type: string
      checkout:
        default: false
        type: boolean
      timeout-minutes:
        default: 360
        type: number
      continue-on-error:
        default: false
        type: boolean
      run-name:
        required: false
        type: string

env:
  GITHUB_TOKEN: ${{ github.token }}
  VARS_JSON: ${{ toJSON(vars) }}

jobs:
  sh:
    if: ${{ inputs.shell == 'sh' }}
    runs-on: ${{ inputs.runs-on }}
    # environment: ${{ inputs.environment }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    continue-on-error: ${{ inputs.continue-on-error }}
    steps:
      - if: ${{ inputs.checkout }}
        uses: actions/checkout@v7
      - run: ${{ inputs.run }}
        shell: sh

  bash:
    if: ${{ inputs.shell == 'bash' }}
    runs-on: ${{ inputs.runs-on }}
    # environment: ${{ inputs.environment }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    continue-on-error: ${{ inputs.continue-on-error }}
    steps:
      - if: ${{ inputs.checkout }}
        uses: actions/checkout@v7
      - run: ${{ inputs.run }}
        shell: bash

  pwsh:
    if: ${{ inputs.shell == 'pwsh' }}
    runs-on: ${{ inputs.runs-on }}
    # environment: ${{ inputs.environment }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    continue-on-error: ${{ inputs.continue-on-error }}
    steps:
      - if: ${{ inputs.checkout }}
        uses: actions/checkout@v7
      - run: ${{ inputs.run }}
        shell: pwsh

  cmd:
    if: ${{ inputs.shell == 'cmd' }}
    runs-on: ${{ inputs.runs-on }}
    # environment: ${{ inputs.environment }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    continue-on-error: ${{ inputs.continue-on-error }}
    steps:
      - if: ${{ inputs.checkout }}
        uses: actions/checkout@v7
      - run: ${{ inputs.run }}
        shell: cmd
