name: Eval

on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        type: string
      shell:
        default: bash
        type: string
      script:
        required: true
        type: string

jobs:
  sh:
    if: ${{ inputs.shell == 'sh' }}
    runs-on: ${{ inputs.runner }}
    steps:
      - run: ${{ inputs.script }}
        shell: sh

  bash:
    if: ${{ inputs.shell == 'bash' }}
    runs-on: ${{ inputs.runner }}
    steps:
      - run: ${{ inputs.script }}
        shell: bash

  pwsh:
    if: ${{ inputs.shell == 'pwsh' }}
    runs-on: ${{ inputs.runner }}
    steps:
      - run: ${{ inputs.script }}
        shell: pwsh

  cmd:
    if: ${{ inputs.shell == 'cmd' }}
    runs-on: ${{ inputs.runner }}
    steps:
      - run: ${{ inputs.script }}
        shell: cmd
