name: Test Runner Fetch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 4' # after every weekly runners-images release (https://github.com/actions/runner-images/releases)

jobs:
  inspect-runner:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - id: runner-fetch
        uses: ./
