name: Test Runner Fetch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 4' # after every weekly runners-images release (https://github.com/actions/runner-images/releases)

jobs:
  inspect-runner:
    strategy:
      fail-fast: false
      matrix:
        os: # from: https://docs.github.com/en/actions/reference/runners
          - ubuntu-latest
          - ubuntu-26.04
          - ubuntu-26.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-slim
          - macos-latest
          - macos-26
          - macos-26-intel
          - macos-15
          - macos-15-intel
          - macos-14
          - xcode-27
          - windows-latest
          - windows-2025
          - windows-2025-vs2026
          - windows-2022
          - windows-11-arm
          - windows-11-vs2026-arm

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - id: runner-fetch
        uses: ./
